version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hospital_postgres
    environment:
      POSTGRES_USER: akash
      POSTGRES_PASSWORD: akash
      POSTGRES_DB: hospital
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: